# Generated by Django 5.1.1 on 2024-10-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_extra_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/extra/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/extra/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/extra/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_images',
            field=models.ImageField(blank=True, null=True, upload_to='products/extra/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
