# Generated by Django 5.1.1 on 2024-09-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desciption', models.TextField(blank=True, null=True)),
                ('button_1', models.URLField(blank=True, max_length=500, null=True)),
                ('button_2', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
