# Generated by Django 5.1.1 on 2024-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herosection',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='herosection',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='hero_section/'),
        ),
    ]
