# Generated by Django 5.1.1 on 2024-10-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='home_banner/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
