# Generated by Django 5.1.1 on 2024-10-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homebanner2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner2',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='home_banner2/'),
        ),
    ]
