# Generated by Django 5.1.1 on 2024-10-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homebanner2_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner2',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
