# Generated by Django 5.1.1 on 2024-10-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homebanner2_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='button_2',
        ),
    ]
